version: '3.9'

# below is the format of DATABASE_URL in .env file
# DATABASE_URL=mysql://root:mySQL@db:3306/testdb

services:
  db:
    image: mysql:latest
    restart: always
    container_name: my_container_name
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_starter
    restart: always # on crash restart the container
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql:
